version: '3.1'
services:
  mydb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: franco19
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: fran
      MYSQL_PASSWORD: franco19
    volumes:
     - C:/Users/Usuario/Desktop/treshermanitos/mysql:/var/lib/mysql
    ports:
     - 3312:3306
  spring-api:
    image: ecommerce-spring
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mydb:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: fran
      SPRING_DATASOURCE_PASSWORD: franco19
    ports:
     - 8000:8080
    depends_on:
     - mydb
